owner: kin-labs
repo: kinetic-upptime

sites:
  - name: Kinetic Devnet
    url: https://devnet.kinetic.kin.org
  - name: Kinetic Mainnet
    url: https://mainnet.kinetic.kin.org
  - name: Kinetic Docs
    url: https://kinetic.kin.org
  - name: Kinetic Demo
    url: https://kinetic.pages.dev

status-website:
  theme: night
  baseUrl: /kinetic-upptime
  logoUrl: https://raw.githubusercontent.com/kintegrate/kin-logos/main/svg/kin-diamond-large-purple.svg
  name: Kinetic
  introTitle: "Kinetic by Kin"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
